### ISSUE TITLE
As a member of the team I want to produce a list of all people, people living in cities and people not living in cities in each continent, region or country; so that the requirements of the coursework are met.

### ISSUE THREAD

**Issue by MikhaRohrs** [OlavJDigranes/SEMCoursework#9]
A population report requires the following columns:

- The name of the continent/region/country
- The total population of the continent/region/country
- The total population of the continent/region/country living in cities, including a %
- The total population of the continent/region/country not living in cities, including a %

**Comment by MikhaRohrs** [comment]
A population report requires the following columns:

- The name of the continent/region/country
- The total population of the continent/region/country
- The total population of the continent/region/country living in cities, including a %
- The total population of the continent/region/country not living in cities, including a %

**Comment by BaToJo-napier** [comment]
Need clarity on how the client wants to define a city. For now I will assume that it means any entry in the City table, even though that list includes a village with 42 people in it.
